### ISSUE TITLE
Auto Install CentOS 7

### ISSUE THREAD

**Issue by willpolley** [DeskPRO/install#6]
Bare install of CentOS 7, fully updated.

Ran auto install, server requirement check page reports major problems.

All folders listed to check are deskpro:deskpro.

Ideas?

**Comment by chrispadfield** [comment]
Can you show a screenshot of the problems reported please.

**Comment by willpolley** [comment]
![](https://docs.google.com/a/newspring.cc/uc?id=0B05-jnbkSD19MkpIMl9CUFp1Y3M)
![](https://docs.google.com/a/newspring.cc/uc?id=0B05-jnbkSD19MjVhMEFGckF3V00)
![](https://docs.google.com/a/newspring.cc/uc?id=0B05-jnbkSD19UWRLZ0J3dUhCVjA)

**Comment by chrispadfield** [comment]
Hi Will,

(We can't replicate). Is this a local install? If so, what iso did you install from, and what settings (e.g. custom SCAP or selinux?).

Can you zip us /var/log/audit/audit.log and attach that and also get the DeskPRO report file please? https://support.deskpro.com/en/kb/articles/generating-a-server-report-file

**Comment by fcoelho** [comment]
Hi Will, instead of uploading audit.log, can you check if `ausearch -m avc` returns any matches?

**Comment by willpolley** [comment]
I'm unable to run the server report as requested since I am unable to run the portal or admin site.

I created a new VMware VM (2 core, 6GB ram) and installed from CentOS 7 minimal media. Updated components from yum update and upgrade. Moved to kernel 4. Then ran the scripted piped into a sudo shell.

ausearch output: [gist](https://gist.github.com/willpolley/bd81d01e917be94d1a71945dbc791d20)

**Comment by fcoelho** [comment]
Thanks, it does seem like something selinux related. Can you run `setenforce 0` just to see if you are then able to generate the server report?

I'm going to try installing into a vm created from the minimal iso as well to see if I can trigger that. How did you "move to kernel 4"? Did you build it yourself or used a package from some third party repository?

**Comment by willpolley** [comment]
Turning off selinux allowed me to move through setup and generate a server report. [dropbox link](https://www.dropbox.com/s/sc34dd08uvzoaqr/deskpro-report.zip?dl=0)

I added the El Repo repository for CentOS 7 in order to upgrade to the v4. (4.7.2-1.el7.elrepo.x86_64 specifically)

**Comment by fcoelho** [comment]
Hi, can you try this and re-enable selinux to see if it fixes your issue?

```
cd /usr/share/nginx/html/deskpro
chcon -R -t httpd_sys_rw_content_t attachments/ var/
```

**Comment by willpolley** [comment]
That fixed it. 

Basic functions such as file upload and download are functioning.

Server requirements page displays a green bar.

**Comment by fcoelho** [comment]
Hi Will, added this to latest installer, thanks for all the info
