### ISSUE TITLE
line 129 BASH_SOURCE[0]: unbound variable

### ISSUE THREAD

**Issue by willpolley** [DeskPRO/install#7]
This occurs on CentOS 7 and Ubuntu Server  16.04.1 LTS.

**Comment by fcoelho** [comment]
Hi Will, this should appear when installing via the `curl | bash` method, although it's a harmless message. In any case, I've pushed e766c26db324465bf2a59ff76cca6d642fc029cc which does a slightly better check and should not show that message in any situation
