### ISSUE TITLE
CentOS 7 Dependancy libsemanage-python

### ISSUE THREAD

**Issue by willpolley** [DeskPRO/install#8]
libsemanage-python is not installed by default on a fresh CentOS 7 minimal install. 

Verified with new build 1611.

When the libsemanage-python is **not** pre-installed, the script does not successfully change SELinux options.

![screen shot 2017-01-19 at 11 39 25 am](https://cloud.githubusercontent.com/assets/859997/22119591/2b3a543a-de4a-11e6-835f-62d3b81979f3.png)

**Comment by fcoelho** [comment]
Thanks again Will, I've pushed the fix on 711231b
